### ISSUE TITLE
Could this be used as a local client?

### ISSUE THREAD

**Issue by lostinblue** [tkerber/golem#27]
Or is it not that developed yet? I was thinking of using a html page as a local client UI instead of QT so have been looking at golang browsers.

**Comment by tkerber** [comment]
It is certainly not developed enough to be used in any serious code, and this is unlikely to change, as I've abandoned the project due to the webkit2gtk APIs being insufficient for what I wanted to do with them.

That being said, depending on how intricate a UI you want, it may be feasible to roll your own. Getting a simple web page embedding working is fairly straightforward; one of the early commits should be basically just that. The difficult part would be relaying information back from the web page to the program back end, as browsers are in general not designed to do that. My first thoughts would be hooking into the javascript, or generating a url request which the backend can catch.
